services:
  auth:
    build:
      context: ./auth
    environment:
      - PORT=5000
    ports:
      - "5000:5000"
    restart: always

  tickets:
    build:
      context: ./tickets
    environment:
      - PORT=5001
    ports:
      - "5001:5001"
    restart: always

  orders:
    build:
      context: ./orders
    environment:
      - PORT=5002
    ports:
      - "5002:5002"
    restart: always

  expiration:
    build:
      context: ./expiration
    environment:
      - PORT=5003
    ports:
      - "5003:5003"
    restart: always

  nats:
    image: nats-streaming:0.17.0
    command:
      [
        "-p",
        "4222",
        "-m",
        "8222",
        "-hbi",
        "5s",
        "-hbt",
        "5s",
        "-hbf",
        "2",
        "-SD",
        "-cid",
        "ticketing",
      ]
    ports:
      - "4222:4222" # NATS client port
      - "8222:8222" # Monitoring port
    restart: unless-stopped

  expiration-redis:
    image: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  auth-mongo:
  tickets-mongo:
  orders-mongo:
