services:
  auth:
    build:
      context: ./auth
    environment:
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      - auth-mongo
      - nginx
    restart: always

  tickets:
    build:
      context: ./tickets
    environment:
      - PORT=5001
    ports:
      - "5001:5001"
    depends_on:
      - tickets-mongo
      - nginx
    restart: always

  orders:
    build:
      context: ./orders
    environment:
      - PORT=5002
    ports:
      - "5002:5002"
    depends_on:
      - orders-mongo
      - nginx
    restart: always

  expiration:
    build:
      context: ./expiration
    environment:
      - PORT=5003
    ports:
      - "5003:5003"
    restart: always

  auth-mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=harun
      - MONGO_INITDB_ROOT_PASSWORD=123456789
    volumes:
      - auth-mongo:/data/db

  tickets-mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=harun
      - MONGO_INITDB_ROOT_PASSWORD=123456789
    volumes:
      - tickets-mongo:/data/db

  orders-mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=harun
      - MONGO_INITDB_ROOT_PASSWORD=123456789
    volumes:
      - orders-mongo:/data/db

  nats:
    image: nats-streaming:0.17.0
    command:
      [
        "-p",
        "4222",
        "-m",
        "8222",
        "-hbi",
        "5s",
        "-hbt",
        "5s",
        "-hbf",
        "2",
        "-SD",
        "-cid",
        "ticketing",
      ]
    ports:
      - "4222:4222" # NATS client port
      - "8222:8222" # Monitoring port
    restart: unless-stopped

  expiration-redis:
    image: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"

volumes:
  auth-mongo:
  tickets-mongo:
  orders-mongo:
