services:
  auth:
    build:
      context: ./auth
      args:
        NODE_ENV: development
    volumes:
      - ./auth:/app
      - /app/node_modules
    environment:
      - JWT_KEY=myjwtsecretkey
      - NODE_ENV=development
      - MONGO_USER=harun
      - MONGO_PASSWORD=123456789
    command: npm run dev
  tickets:
    build:
      context: ./tickets
      args:
        NODE_ENV: development
    volumes:
      - ./tickets:/app
      - /app/node_modules
    environment:
      - JWT_KEY=myjwtsecretkey
      - NODE_ENV=development
      - MONGO_USER=harun
      - MONGO_PASSWORD=123456789
      - NATS_CLUSTER_ID=ticketing
      - NATS_CLIENT_URL=http://nats:4222
      - NATS_CLIENT_ID=tickets
    command: npm run dev

  orders:
    build:
      context: ./orders
      args:
        NODE_ENV: development
    volumes:
      - ./orders:/app
      - /app/node_modules
    environment:
      - JWT_KEY=myjwtsecretkey
      - NODE_ENV=development
      - MONGO_USER=harun
      - MONGO_PASSWORD=123456789
      - NATS_CLUSTER_ID=ticketing
      - NATS_CLIENT_URL=http://nats:4222
      - NATS_CLIENT_ID=orders
    command: npm run dev

  expiration:
    build:
      context: ./expiration
      args:
        NODE_ENV: development
    volumes:
      - ./expiration:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NATS_CLUSTER_ID=ticketing
      - NATS_CLIENT_URL=http://nats:4222
      - NATS_CLIENT_ID=expiration
      - REDIS_HOST=expiration-redis
    command: npm run dev
